### ISSUE TITLE
Maybe a problem with mdx?

### ISSUE THREAD

**Issue by OBACodes** [novuhq/website#5]
Following the instructions, ran into errors regarding @mdx-js not found (I cloned today, and ran `npm install` today).

I manually installed mdx and ran into this:
```
Error in ".../node_modules/gatsby-plugin-mdx/gatsby-node.js": Must use import to load ES Module:
.../website/node_modules/@mdx-js/mdx/index.js
```

I know Gatsby had issues with mdx in the past so might be related?  thanks a bunch 🙏

**Comment by OBACodes** [comment]
See relevant:
https://github.com/gatsbyjs/gatsby/issues/34706#issuecomment-1029716942

**Comment by andrewgolovanov** [comment]
Hi @OBACodes!

Thanks for your feedback :raised_hands:

It seems that when installing dependencies the`package.lock` file stores `v2` instead of `v1` for `@mdx-js/mdx` and `@mdx-js/react` which is what is causing this problem, as the `gatsby-plugin-mdx` plugin currently requires exactly `v1` to work properly

We've updated the `package.json` file and added the right dependencies with the right version to successfully build the project to avoid possible conflicts between dependencies.

Please let me know if you still have problems running the project
Thanks!
